#!/bin/bash

br=`git branch | grep '^*' | cut -d ' ' -f 2`
if [ $br == "master" ]; then
    echo 'Copy notes to dropbox on master branch'
    rsync -a --delete --exclude=.git --exclude=.gitignore --exclude=.DS_Store /ws/OrgNotes/ ~/Dropbox/Apps/beorg
fi
