# extrakto filter definitions

# Define your own filters in ~/.config/extrakto/extrakto.conf
# To override an existing filter just specify the new values.
# For example, if you prefer to split words on comma as well you can define:
# [word]
# regex: ([^][(){}=$─-➿-, \t\n\r]+)

# define a section per filter
# each filter must have at least a regex containing one or more capture groups
# regex:      a python regex expression
# enabled:    is filter active (default True)
# in_all:     is included in --all (default True)
# lstrip:     characters to strip from left result
# rstrip:     characters to strip from right result
# exclude:    exclude result if matching
# alt2-9:     alternate result (see url)
# min_length: minimum length of the result (default 5)

[command]
regex: `([^`]+)`
